### ISSUE TITLE
ask hangs sometimes with block_on

### ISSUE THREAD

**Issue by thedavidmeister** [riker-rs/riker-patterns#2]
minimum repro tests at #1 

the test runs a few thousand asks, but i've seen things hang with fewer than 5 iterations

whether it hangs is non-deterministic

AFAIK i've taken the code straight from the docs here :/

**Comment by leenozara** [comment]
Thanks or testing that. I'll recreate it and see where it is hanging.

**Comment by leenozara** [comment]
@thedavidmeister FYI the hanging can be recreated and the reason has been identified. Today's `0.1.6` still has the hang issue but we're closer to resolving it. Sorry it's taking time - it's been more difficult than expected to resolve. Please hang tight, it'll be fixed soon.

**Comment by leenozara** [comment]
@thedavidmeister I can confirm that Riker `0.1.7` fixes this hang issue. Can you also confirm? Thanks!

**Comment by thedavidmeister** [comment]
works for me in the HC branch, nice work! @leenozara

**Comment by leenozara** [comment]
Closing this issue based on participants' testings.
